[package]
name = "github-release-download"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
color-eyre = "0.5.11"
indicatif = "0.16.2"
reqwest ={ version = "0.11.4", features = ["json"] }
serde = { version = "1.0.126", features = ["derive"] }
skim = "0.9.4"
structopt = "0.3.21"
tokio = { version = "1.7.0", features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "grd"
path = "src/main.rs"
