[package]
name = "github-update"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.0-rc.2", features = ["derive"] }
color-eyre = "0.6.2"
dirs = "4.0.0"
indicatif = "0.17.1"
once_cell = "1.15.0"
regex = "1.6.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_regex = "1.1.0"
skim = "0.10.1"
thiserror = "1.0.36"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
toml = "0.5.9"

[[bin]]
name = "grd"
path = "src/bin/grd.rs"

[[bin]]
name = "github-update"
path = "src/bin/github-update.rs"
