[package]
name = "github-release-download"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
indicatif = "0.11.0"
reqwest = "0.9.20"
serde = { version = "1.0.111", features = ["derive"] }
skim = "0.6.8"
structopt = "0.3.0"

[[bin]]
name = "grd"
path = "src/main.rs"
