[package]
name = "github-update"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
color-eyre = "0.5.11"
dirs = "3.0.2"
indicatif = "0.16.2"
once_cell = "1.8.0"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_regex = "1.1.0"
skim = "0.9.4"
structopt = "0.3.22"
thiserror = "1.0.26"
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread"] }
toml = "0.5.8"

[[bin]]
name = "grd"
path = "src/bin/grd.rs"

[[bin]]
name = "github-update"
path = "src/bin/github-update.rs"
