[package]
name = "github-update"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.11", features = ["derive"] }
color-eyre = "0.6.2"
dirs = "4.0.0"
indicatif = "0.17.3"
once_cell = "1.17.1"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_regex = "1.1.0"
skim = "0.10.4"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
toml = "0.7.3"

[[bin]]
name = "grd"
path = "src/bin/grd.rs"

[[bin]]
name = "github-update"
path = "src/bin/github-update.rs"
