[package]
name = "github-update"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.1", features = ["derive"] }
color-eyre = "0.6.2"
dirs = "5.0.1"
indicatif = "0.17.5"
once_cell = "1.17.2"
regex = "1.8.3"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_regex = "1.1.0"
skim = "0.10.4"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
toml = "0.7.4"

[[bin]]
name = "grd"
path = "src/bin/grd.rs"

[[bin]]
name = "github-update"
path = "src/bin/github-update.rs"
